name: CI

on:
  push:
  pull_request:

jobs:
  project-history:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: | 
          make test_unit
          make test_acceptance
        working-directory: services/project-history