name: CI

on:
  push:
  pull_request:

jobs:
  project-history:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - run: |
          make test_unit
          make test_acceptance
        working-directory: services/project-history
